name: 'AWS SSM Remote Port Forward Action'
description: 'Starts an AWS SSM remote port forwarding session to a host'
author: 'abizer'
inputs:
  target:
    description: 'The AWS instance to port forward through (e.g., an EC2 instance ID or ECS task ARN)'
    required: true
  host:
    description: 'The remote host to connect to (e.g., an RDS instance endpoint)'
    required: true
  local-port:
    description: 'The local port to forward to the remote host'
    required: true
  remote-port:
    description: 'The remote port on the host to connect to'
    required: true
  aws-region:
    description: 'The AWS region to use'
    required: true
  command:
    description: 'The command to run while the port forwarding tunnel is active'
    required: true
outputs:
  command-exit-code:
    description: 'The exit code of the command that was run'
  command-stdout:
    description: 'The stdout output of the command that was run'
  command-stderr:
    description: 'The stderr output of the command that was run'
runs:
  using: 'node20'
  main: 'dist/index.js'
